### ISSUE TITLE
Adapt to use connector-sdk

### ISSUE THREAD

**Issue by alexellis** [openfaas-incubator/kafka-connector#15]
The connector-sdk was spun out of this project as a generic SDK / library for handling events.

It could now be re-vendored back into the Kafka connector project to reduce the amount of code and to be one of the first example projects using the sdk.

https://github.com/openfaas-incubator/connector-sdk

**Comment by alexellis** [comment]
As far as I'm aware John is not working on this and is too busy to look at it.

This is fair game for anyone who can make the change and run through the README afterwards to prove it worked 👍 

You'll need to:

* vendor/revendor the latest release of the connector-sdk as linked above using `dep`
* adapt the connector to use the types which were removed and added to packages in connector-sdk - use the example in connector-sdk as a template
* test the changes using the README instructions

Feel free to ask for help on Slack or here.

**Comment by tessellator** [comment]
@alexellis I would like to try this one. 

One minor difference between kafka-connector and connector-sdk is the presence of the Topics function on TopicMap (added to kafka-connector in [this commit](https://github.com/openfaas-incubator/kafka-connector/commit/5c372fe992f10a761570838c58394e1695d85788)). Would you be open to a PR to add that function to connector-sdk, or should I keep it local to kafka-connector?

**Comment by rgee0** [comment]
Derek close: resolved by #25
