### ISSUE TITLE
Kafka 2.1.0 not working with connector. 

### ISSUE THREAD

**Issue by franciszka-piasecka** [openfaas-incubator/kafka-connector#17]
We've been using kafka-connector on kubernetes to trigger functions in our project with no issues as long as Kafka was on 1.x version.  However upgrading to 2.10 caused the connector to log following error:
```
consumer error:  kafka: error while consuming faas-request/10: kafka: error decoding packet: CRC didn't match expected 0x0 got 0xe38a6876
```
several times a second on all trigger topics. Reverting back to 1.x has solved the problem. Is Kafka 2.x supported? I can't find any information saying that it isn't.

**Comment by johnmccabe** [comment]
Hi @franciszka-piasecka are you running Apache Kafka or Confluent Platform?

**Comment by johnmccabe** [comment]
Never mind, I've replicated the issue locally, have a closer look now.
```
consumer error:  kafka: error while consuming faas-request/0: kafka: error decoding packet: CRC didn't match expected 0x0 got 0xe38a6876
```

**Comment by johnmccabe** [comment]
Ok, I have a fix, need to do some testing on Kafka 1.x as well and I'll raise a PR.
```
[#2] Received on [faas-request,0]: 'kafka 2.x'
2018/12/12 00:50:37 Invoke function: figlet
2018/12/12 00:50:37 Response [200] from figlet  _          __ _           ____
| | ____ _ / _| | ____ _  |___ \  __  __
| |/ / _` | |_| |/ / _` |   __) | \ \/ /
|   < (_| |  _|   < (_| |  / __/ _ >  <
|_|\_\__,_|_| |_|\_\__,_| |_____(_)_/\_\

2018/12/12 00:50:37 Syncing topic map
```

**Comment by johnmccabe** [comment]
The upstream issue was fixed here https://github.com/Shopify/sarama/pull/1149 will raise a PR shortly.
