### ISSUE TITLE
support multi brokers and different ports

### ISSUE THREAD

**Issue by hc-chien** [openfaas-incubator/kafka-connector#21]
need to support multiple brokers and different ports

**Comment by martindekov** [comment]
I needed this for my use-case so I implemented it. Should I open a PR with the change? Or keep it to myself?

**Comment by martindekov** [comment]
Hey there @hc-chien . Do you mind me closing the Issue and opening another one? I will add more detail and will reference it to this one.

**Comment by martindekov** [comment]
Hey @hc-chien I will be closing the Issue and re-open it with more detail.

**Comment by martindekov** [comment]
Derek close

**Comment by martindekov** [comment]
Opened PR for this 👍
