### ISSUE TITLE
Add helm chart

### ISSUE THREAD

**Issue by alexellis** [openfaas-incubator/kafka-connector#22]
We should generate a helm chart and use it for installing the connector.

See the faas-netes repo for an example of what this may look like.

* Generate helm chart
* Template required values 
* Update Makefile

**Comment by roncrivera** [comment]
hi @alexellis, i can work on this. thanks!

**Comment by ivanayov** [comment]
Hi @roncrivera 
How is this going, do you need any help?

**Comment by roncrivera** [comment]
> Hi @roncrivera
> How is this going, do you need any help?

Hi @ivanayov, 

I am still working on this, aiming to submit a PR over the weekend. My apologies for the delay.

**Comment by ivanayov** [comment]
@roncrivera It's fine, I'm just asking if you're blocked or having any issues we can help with :)
