### ISSUE TITLE
Move to annotations

### ISSUE THREAD

**Issue by alexellis** [openfaas-incubator/kafka-connector#3]
OpenFaaS now has support for annotations meaning we can use a rich value for the topic list.

- faas-swarm 0.4.0
- faas-netes 0.6.0
- openfaas-operator (awaiting review & merge)

This task means changing the code to look at the function's topic value in an annotation instead of a label.

It should be a straight-forward change plus basic smoke testing on Kubernetes and Swarm.

**Comment by ivanayov** [comment]
I can work on this
