### ISSUE TITLE
Question: does scaling happen based upon topic length?

### ISSUE THREAD

**Issue by kameshchauhan** [openfaas-incubator/kafka-connector#35]
I am evaluating the Kafka-Connector as part of OpenFaaS initiative. The aspect to be checked is that if the source of messages is generating messages at a rate higher than the sink can consume (in other terms the replica is not sufficiently defined), then what is the performance impact?

## Expected Behaviour
The auto-scaling should also consider the size of the topic (i.e. pending message on the topic).

## Current Behaviour
The auto-scaling is happening based on request/query metrics or resource utilization.

## Possible Solution
The idler component can be made to check the size of the kafka topic somehow and should manage auto-scaling replica based on the expected QOS defined may be in stack.yaml file.

**Comment by alexellis** [comment]
Hi Kamesh,

We have several options for this including #27 where messages can be ingested into the internal asynchronous queue of NATS Streaming for processing when capacity is available.

Auto-scaling is enabled in the gateway and is based upon QPS at the gateway. The connector calls through to the gateway and will cause auto-scaling based upon that demand.

Alex
