### ISSUE TITLE
Connector does not sync topic map properly

### ISSUE THREAD

**Issue by martindekov** [openfaas-incubator/kafka-connector#40]
I need to run my workflow e2e with the kafka-connector and stumbled upon an issue.

## Expected Behaviour

Invoke the function through producing topics

## Current Behaviour

Function is not invoked

## Possible Solution

Not sure where but, I believe it is something in the connector-sdk.

## Steps to Reproduce (for bugs)

Kafka Connector Default environment is applied properly 
```
...
    Environment:
      gateway_url:        http://gateway.openfaas:8080
      topics:             faas-request
      print_response:     true
      basic_auth:         true
      secret_mount_path:  /var/secrets
      broker_host:        kafka
...
```
1. Inside `kafka-connector/yaml/kubernetes`
```
kubectl apply -f kafka-broker-dep.yml,kafka-broker-svc.yml,zookeeper-dep.yaml,zookeeper-svc.yaml
```
2. Install kafka connector with Helm
```
helm repo add openfaas https://openfaas.github.io/faas-netes/ &&
 helm upgrade kafka-connector openfaas/kafka-connector 
    --install 
    --namespace openfaas
```
3. Deploy function with annotation `faas-request`(default)
```
faas store deploy figlet --annotation topic=faas-request
```
4. Check connector logs 
```
kubectl logs $(kubectl get pods -o name -n openfaas | grep -m1 kafka-connector | cut -d'/' -f 2) -n openfaas --tail 100 -f
```
5. Exec in producer and produce payloads
```
kubectl exec -n openfaas -t -i $(kubectl get pods -n openfaas -l component=kafka-broker -o name|cut -d'/' -f2) -- /opt/kafka_2.12-0.11.0.1/bin/kafka-console-producer.sh --broker-list kafka:9092 --topic faas-request
```

## Context

Trying to go through Kafka Blog workflow

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):
dev
* Kafka version and configuration:
0.10.0.2 I believe taken from the yaml files in the repo
* Docker version `docker version` (e.g. Docker 17.0.05 ):
18
* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
Kubernetes
* Operating System and version (e.g. Linux, Windows, MacOS):
Linux
* Link to your project or a code example to reproduce issue:

* Please also follow the [troubleshooting guide](https://github.com/openfaas/faas/blob/master/guide/troubleshooting.md) and paste in any other diagnostic information you have:

**Comment by alexellis** [comment]
@zeerorg / @martindekov / @matipan please can you add CI to the Kafka-connector to run an e2e test like we have with faas-netes?

**Comment by rgee0** [comment]
Just followed the repro steps and...

```
2019/04/07 14:05:15 Invoke function: figlet
[#2] Received on [faas-request,0]: 'hello'
2019/04/07 14:05:15 connector-sdk got result: [200] faas-request => figlet (138) bytes
2019/04/07 14:05:16 Syncing topic map
```
Looks like the function is invoked but the `print_response` directive is ignored?

**Comment by martindekov** [comment]
I am not going to be able to implement the CI I already assigned myself Issue with the templates plus talked with Matias for the branches thing I haven't been able to look at any of those due to problems with swap memory for my GitLab instance and the Blog Post workflow.

**Comment by alexellis** [comment]
It may be easier for @zeerorg to add the CI since he helped me do it for faas-netes. 

Have you updated your helm chart repo yet? What does `helm search openfaas` give?

**Comment by martindekov** [comment]
```
helm search openfaas
NAME                            CHART VERSION   APP VERSION     DESCRIPTION
local/openfaas                  1.3.3                           Enable Kubernetes as a backend for OpenFaaS (Functions as...
openfaas/openfaas               3.0.0                           Enable Kubernetes as a backend for OpenFaaS (Functions as...
openfaas/kafka-connector        0.1.2                           Connect OpenFaaS functions to Kafka topics
```
Strange `0.1.2` this is it

**Comment by martindekov** [comment]
But `helm repo delete openfaas` and `helm repo add openfaas` does not update the Chart version, probably I am doing something wrong.

**Comment by martindekov** [comment]
Derek close

**Comment by rgee0** [comment]
Output here:
```
$ helm search openfaas
NAME                    	CHART VERSION	APP VERSION	DESCRIPTION                                                 
openfaas/openfaas       	3.0.0        	           	Enable Kubernetes as a backend for OpenFaaS (Functions as...
openfaas/kafka-connector	0.1.2        	           	Connect OpenFaaS functions to Kafka topics
```

**Comment by martindekov** [comment]
Ah this is a chart version ..

**Comment by martindekov** [comment]
Derek reopen

**Comment by alexellis** [comment]
I update with: `help repo update openfaas` - 0.1.2 is the latest version.

**Comment by martindekov** [comment]
Yeah forgot that this is Charts version otherwise thats the error from the producer
```
>asd
[2019-04-07 15:05:43,254] ERROR Error when sending message to topic faas-request with key: null, value: 3 bytes with error: (org.apache.kafka.clients.producer.internals.ErrorLoggingCallback)
org.apache.kafka.common.errors.TimeoutException: Failed to update metadata after 60000 ms.
```

**Comment by alexellis** [comment]
So what's the latest? I read that @rgee0 can't reproduce the error?

**Comment by martindekov** [comment]
Still not able to invoke functions, I applied the `connector-dep.yml` still the same thing. Tore down my OpenFaaS instance and brought it back up with the exact steps provided in the Issue still not able to invoke function.

**Comment by martindekov** [comment]
Ok tested the image itself by applying `connector-dep.yml` file instead of deploying with charts in non Minikube Kubernetes cluster and it invokes functions as it should by generating load on a tpoic so the functionality is intact so I will close the issue.

**Comment by martindekov** [comment]
Derek close

**Comment by martindekov** [comment]
I think we should add
```
            - name: print_response_body
              value: "true"
```
to `values.yml`?
