### ISSUE TITLE
kafka-connector CrashLoopBackOff when basic authentication is turned off by user

### ISSUE THREAD

**Issue by kushalarya** [openfaas-incubator/kafka-connector#50]
Kafka-connector pod is not starting. Here are the logs from Kafka-connector pod 

```
2019/07/19 12:42:34 invalid character 'E' looking for beginning of value
```

Basic auth is turned off.
I'm running this on Bare metal k8s cluster. 

Please advise

**Comment by alexellis** [comment]
Please start again and turn authentication on. Your setup is insecure.

**Comment by alexellis** [comment]
/set title: kafka-connector CrashLoopBackOff when basic authentication is turned off by user

**Comment by kushalarya** [comment]
@alexellis Still the same thing in logs

**Comment by martindekov** [comment]
Hello @kushalarya I will try to replicate.

Your gateway has the basic-auth turned off I presume? Also you have set up the `basic_auth` variable to false?

Regards,
Martin

**Comment by alexellis** [comment]
Please move over to your colleague / friend's issue now: https://github.com/openfaas/faas-netes/issues/479
