### ISSUE TITLE
Bind the kafka-connector to existing kafka topic

### ISSUE THREAD

**Issue by vanc3yan9** [openfaas-incubator/kafka-connector#52]
I have already got a kafka service running on another machine via `docker-compose up` mode, and I just wonder if I could bind the `kafka-connector` to the topic in the running kafka service and how? Thanks a lot!

**Comment by alexellis** [comment]
Hi @vanc3yan9 you can pick the name of the topics that your connector listens to.

Hopefully you'll find this blog post useful https://www.openfaas.com/blog/kafka-connector/

For further technical support, please join Slack

Alex

**Comment by vanc3yan9** [comment]
> /msg: slack



> Hi @vanc3yan9 you can pick the name of the topics that your connector listens to.
> 
> Hopefully you'll find this blog post useful https://www.openfaas.com/blog/kafka-connector/
> 
> For further technical support, please join Slack
> 
> Alex

It really helps! Thx a lot!
