### ISSUE TITLE
Migrate extensions/v1beta1 resources to apps/v1 API

### ISSUE THREAD

**Issue by simoncas** [openfaas-incubator/kafka-connector#56]
The Kubernetes v1.16 release has stopped serving the deprecated API `extensions/v1beta1` in favor of `apps/v1`.

## Expected Behaviour
We should migrate the following Kubernetes Deployment to `apps/v1`  to be compatible with Kubernetes v1.16+

*  `kafka-broker-dep.yml`
*  `zookeeper-dep.yaml`
 * `connector-dep.yml`

For your information `apps/v1` is GA since [Kubernetes 1.9](https://kubernetes.io/blog/2017/12/kubernetes-19-workloads-expanded-ecosystem/)

## Current Behaviour
It's not possible to deploy the kafka connector using the actual version of the Deployment under `kafka-connector/yaml/kubernetes/` to a kubernetes running v1.16.

The following error occurs:

`no matches for kind "Deployment" in version "extensions/v1beta1"`

## Possible Solution
Migrate the 3 Deployments to apps/v1. (I'm ready to submit a PR)

## Steps to Reproduce (for bugs)

1. k8s 1.16+
2. kubectl apply -f ./yaml/kubernetes/

## Context
I've encountered the error while deploying the kafka-connector using `kubectl apply -f ./yaml/kubernetes/`

I also had to upgrade zookeeper to the latest version `wurstmeister/zookeeper:latest` since the `wurstmeister/zookeeper:3.4.6` failed to start.  (Same behavior as described here #47)
I also updated kafka version to `wurstmeister/kafka:2.12-2.3.0` without encountering any problems. 

I have a PR ready to submit with the following changes:
* Upgrade Deployments to apps/v1 (we just need to add the `selector` field)
* Upgrade Zookeeper image to `wurstmeister/zookeeper:latest`
* Upgrade Kafka image to `wurstmeister/kafka:2.12-2.3.0`

 
## Your Environment

* Are you using Docker Swarm or Kubernetes (FaaS-netes)? Kubernetes v1.16.2

* Operating System and version (e.g. Linux, Windows, MacOS): MacOS

**Comment by alexellis** [comment]
I'm happy for you to update the Kubernetes YAML files, I don't believe that K8s 1.16 is available on any managed clouds yet, but making the upgrade is fine and we've done it for several other components like openfaas and openfaas-cloud already.

**Comment by alexellis** [comment]
cc @martindekov

**Comment by alexellis** [comment]
For the Docker image version, we've not had anyone else report that yet. I'm OK with updating, but it really needs to be to a pinned version number (`:latest` is unpredictable) and ideally under a separate issue, if you can open another.

**Comment by martindekov** [comment]
I agree for the separation of Issues, I can check put the changes if PR is submitted 👍

**Comment by simoncas** [comment]
Unfortunately the `wurstmeister/zookeeper:latest` doesn't have a pinned version. https://hub.docker.com/r/wurstmeister/zookeeper/tags.
Yes I will open a separate issue for the Docker image version

**Comment by martindekov** [comment]
Thank you @simoncas

**Comment by alexellis** [comment]
@simoncas I can see that they have one image from 4 years ago and latest, so let's use `latest` - but perhaps pin to the SHA digest instead?

**Comment by simoncas** [comment]
Yes I will try to use the SHA digest, this is more secure

**Comment by alexellis** [comment]
Example of how the SHA can be used with `kubectl run` - kubectl run test -t -i --image index.docker.io/library/bash@sha256:d6696f7ac04ec9753f56c6bb2ab69b4f03a39a14a3dd72341bb41b9f6855def9

**Comment by alexellis** [comment]
@simoncas do you have a PR yet for us?

**Comment by simoncas** [comment]
@alexellis Yes sorry for the delay, I will try to do it today.

**Comment by alexellis** [comment]
@simoncas where are we with this now?
